language: node_js
sudo: false
node_js:
  - '0.11'
  - '0.12'
  - iojs

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true
  allow_failures:
    - node_js: iojs

install:
  - npm install
  - npm install bower -g
  - bower install

script:
  - npm test
