language: node_js
sudo: false
node_js:
  - '0.10'
  - '0.12'
  - iojs

cache:
  directories:
    - node_modules
    - test/tmp/deps/node_modules

matrix:
  fast_finish: true
  allow_failures:
    - node_js: iojs

install:
  # Disable the spinner, it looks bad on Travis
  - npm config set spin false
  - npm install -g npm@latest
  - npm install typescript -g
  - tsd install

before_script:
  - gem install sass
  - npm install -g bower
  - npm install -g gulp

script:
  - npm test

after_success:
  - npm run coveralls
